INPUTSTATE_OPEN = 'OPEN'
INPUTSTATE_MOUSEDOWN = 'MOUSEDOWN'
TITLEBAR = "Menlo's Book"

ASSET_STATE_OPEN = 'OPEN'
ASSET_STATE_BUSY = 'BUSY'
ASSET_TYPE_TILESET = 'TILESET'

VIEWSTATE_UNINITIALIZED = 'UNINITIALIZED'
VIEWSTATE_LOADING_ASSETS = 'LOADING'
VIEWSTATE_UPDATING_DISPLAY = 'UPDATING'
VIEWSTATE_READY = 'READY'
VIEWSTATE_RUNNING = "RUNNING"

GAMESTATE_STARTUP = 'START'
GAMESTATE_LOADING_CONFIG = 'CONFIGLOADING'
GAMESTATE_CONFIG_LOADED = "CONFIGLOADED"
GAMESTATE_WAITINGONVIEW = 'INITDISPLAY'
GAMESTATE_LOADING_ASSETS = 'ASSETSLOADING'
GAMESTATE_BUILDING_MODEL = 'BUILDING'
GAMESTATE_LOADING_LEVEL = 'LOADING'
GAMESTATE_RUNNING = 'RUNNING'

DIRECTION_N = 0
DIRECTION_S = 1
DIRECTION_E = 2
DIRECTION_W = 3
DIRECTION_NE = 4
DIRECTION_SE = 5
DIRECTION_NW = 6
DIRECTION_SW = 7

TILE_X = 32
TILE_Y = 32
